version: '3'

services:
  djangoapp:
    build: .
    image: &djangoapp djangoapp
    entrypoint: /django_entrypoint.sh
    env_file:
      - config/worker/worker_env
    volumes:
      - .:/opt/services/djangoapp/src
      - ./static:/opt/services/static
      - ./media:/opt/services/media 
    networks:
      - nginx_network
      - database1_network 
      - broker_network
    depends_on:  
      - database1
      - broker

  nginx:
    image: nginx:1.13
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./static:/opt/services/static
      - ./media:/opt/services/media 
    depends_on:
      - djangoapp
    networks:
      - nginx_network

  database1: 
    image: postgres:10
    env_file:  
      - config/db/fulfildb_env
    networks:  
      - database1_network
    volumes:
      - ./database:/var/lib/postgresql/data

    
  flower:
    image: zoomeranalytics/flower:0.9.1-4.0.2
    restart: "no"
    env_file:
       - config/worker/worker_env
    ports:
      - "5555:5555"
    depends_on:
      - broker
    networks: 
      - broker_network

  broker:
    image: rabbitmq:3
    env_file: 
       - config/worker/worker_env
    ports:
      - 5672:5672
    networks: 
      - broker_network


networks: 
  nginx_network:
    driver: bridge
  database1_network: 
    driver: bridge
  broker_network:
    driver: bridge
