# Generated by Django 2.2.2 on 2019-06-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('sku', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(default='no name', max_length=30)),
                ('description', models.TextField(default='no description')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
            ],
        ),
    ]
