# Generated by Django 2.2.2 on 2019-06-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_product_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='elements',
            field=models.IntegerField(default=0),
        ),
    ]
