# Generated by Django 2.2.2 on 2019-06-13 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190613_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.Document'),
        ),
    ]
